### ISSUE TITLE
您好，我看你嗯这篇应该是刷爆所有算法了吧，应该是最高分的代码了

### ISSUE THREAD

**Issue by StormArcher** [weijun88/F3Net#1]

**Comment by weijun-arc** [comment]
ICCV2019上有几篇新的关于显著性目标检测的文章, 您可以去看看

**Comment by StormArcher** [comment]
您好，您论文里面的那个阿尔法函数的图（红蓝类似热度图）做的很漂亮，那个显示像素重要程度的代码能否分享一下

**Comment by StormArcher** [comment]
为什么训练过程这么快才2个多小时

**Comment by StormArcher** [comment]
但是结果很不理想，与您的模型差了几个百分点，是我训练技巧的原因吗？

**Comment by weijun-arc** [comment]
能把你的实验结果贴出来吗？包括数据集及其对应指标的精度

**Comment by StormArcher** [comment]
是这样的，我看错了，差得不太多，每次训练的结果不太一样吧
=>F3Net(作者提供的模型)
ECSSD     dataset with DSS method get| 0.9432 max-fmeasure| 0.0341 mae| 0.9220 S-measure| 0.9483 max-Emeasure..
PASCALS   dataset with DSS method get| 0.8672 max-fmeasure| 0.0619 mae| 0.8597 S-measure| 0.8933 max-Emeasure..
DUT-OMRON dataset with DSS method get| 0.8033 max-fmeasure| 0.0525 mae| 0.8384 S-measure| 0.8628 max-Emeasure..
HKU-IS    dataset with DSS method get| 0.9352 max-fmeasure| 0.0281 mae| 0.9171 S-measure| 0.9529 max-Emeasure..
DUTS-TE   dataset with DSS method get| 0.8879 max-fmeasure| 0.0355 mae| 0.8875 S-measure| 0.9189 max-Emeasure..

=>F3Net(未改动模型重训练)
ECSSD     dataset with DSS method get| 0.9438 max-fmeasure| 0.0339 mae| 0.9235 S-measure| 0.9499 max-Emeasure..
PASCALS   dataset with DSS method get| 0.8660 max-fmeasure| 0.0639 mae| 0.8570 S-measure| 0.8906 max-Emeasure..
DUT-OMRON dataset with DSS method get| 0.8007 max-fmeasure| 0.0629 mae| 0.8297 S-measure| 0.8547 max-Emeasure..
HKU-IS    dataset with DSS method get| 0.9340 max-fmeasure| 0.0291 mae| 0.9165 S-measure| 0.9526 max-Emeasure..
DUTS-TE   dataset with DSS method get| 0.8847 max-fmeasure| 0.0397 mae| 0.8825 S-measure| 0.9131 max-Emeasure..

**Comment by weijun-arc** [comment]
1. 是的，我们也注意到有些数据集的指标在训练过程中波动较大，你可以多训几次
2. 关于显示热力图部分代码没保存下来，你可以使用opencv的cv2.applyColorMap函数将二值图转化为伪彩色，然后叠加到原图上即可
3.关于速度部分，因为我们使用的batch size较大，总共迭代次数也比较少，所以训练起来比较快

**Comment by StormArcher** [comment]
感谢解惑，非常优秀的算法

**Comment by StormArcher** [comment]
能否加下qq，以后多向您学习910997316
