### ISSUE TITLE
I have a question about the model's performance 

### ISSUE THREAD

**Issue by LiuTingWed** [weijun88/F3Net#17]
good job!
I have a question about the model's performance 
I can't not get same result when i load the model-32 to get predict maps or directly download predict maps.
the former situation which is evaluated in DUTS
Maxf :0.881     MeanF:0.829    MAE:0.036
the latter situation which is evaluated in DUTS
Maxf :0.891     MeanF:0.84    MAE:0.035

**Comment by weijun-arc** [comment]
I have try to evaluate the model performance using model-32 from Baidu and Google drive. Both get the same results:
Maxf :0.891 MeanF:0.84 MAE:0.035
Maybe you need to check your code or model again.
