### ISSUE TITLE
想请教下您关于pasca-s数据集上的一个问题

### ISSUE THREAD

**Issue by aflyingnoob** [weijun88/F3Net#19]
![12](https://user-images.githubusercontent.com/30976978/98328319-6c27d180-2030-11eb-8ef2-04018fa4bb4d.png)
如图，pascal给的mask都是这种不是纯黑白色的图，这种要怎么处理？其他四个数据集都是纯黑白的mask比较好。

**Comment by weijun-arc** [comment]
https://blog.csdn.net/kouyi5627/article/details/93966732
这里有别人处理好的数据集

**Comment by aflyingnoob** [comment]
666
