### ISSUE TITLE
question about train.py

### ISSUE THREAD

**Issue by Wangbo-CASIA** [weijun88/F3Net#2]
thanks for your code!!!
i have a question about your code of train.py, 
`        if epoch>cfg.epoch/3*2:
            torch.save(net.state_dict(), cfg.savepath+'/model-'+str(epoch+1))`

it mean save all the checkpoint when epoch>cfg.epoch/3*2, but how to choose a better one for test?

**Comment by Wangbo-CASIA** [comment]
Besides, when i run train.py, the show of learning  rate "optimizer.param_groups[0]['lr']" is rising? does it something wrong about it?

**Comment by weijun-arc** [comment]
We directly choose the last one for testing
