### ISSUE TITLE
Could you share the code for drawing precision-recall and F-measure curves?

### ISSUE THREAD

**Issue by ZhaiTianLin** [weijun88/F3Net#20]
I've searched for a long time, but I failed. Thanks,

**Comment by weijun88** [comment]
import os
import numpy as np
import scipy.io as sio
import matplotlib.pyplot as plt

# 'blue', 'green', 'purple', 'black', 'cyan', 'mistyrose', 'pink', 'gold', 'magenta', 'darkorange', 'dimgray', 'lime'

# dataset    = ['ECSSD', 'PASCAL-S', 'DUTS', 'HKU-IS', 'DUT-OMRON']
# algorithm  = ['C2SNet', 'RAS', 'R3Net', 'PiCA-R', 'BMPM', 'DGRL', 'PAGE', 'AFNet', 'TDBU', 'PoolNet', 'BASNet', 'CPD-R', 'Ours']
# colors     = ['blue', 'green', 'purple', 'gold', 'black', 'cyan', 'blue', 'green', 'purple', 'gold', 'black', 'cyan', 'red'] 
# linestyles = ['-', '-', '-', '-', '-', '-', '--', '--', '--', '--', '--', '--', '-']
# linewidths = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
# axisPR     = [[0.0, 1.0, 0.8, 1.0], [0.0, 1.0, 0.5, 0.95], [0.0, 1.0, 0.5, 1.0], [0.0, 1.0, 0.8, 1.0], [0.0, 1.0, 0.3, 0.9]]
# axisFT     = [[0.0, 255.0, 0.75, 0.95], [0.0, 255.0, 0.70, 0.88], [0.0, 255.0, 0.6, 0.9], [0.0, 255.0, 0.7, 0.95], [0.0, 255.0, 0.60, 0.83]]

dataset    = ['ECSSD', 'PASCAL-S', 'DUTS', 'HKU-IS', 'DUT-OMRON']
algorithm  = ['C2SNet', 'RAS', 'R3Net', 'PiCA-R', 'BMPM', 'DGRL', 'PAGE', 'AFNet', 'TDBU', 'PoolNet', 'BASNet', 'CPD-R', 'APN']
colors     = ['blue', 'green', 'purple', 'gold', 'black', 'cyan', 'blue', 'green', 'purple', 'gold', 'black', 'cyan', 'red'] 
linestyles = ['-', '-', '-', '-', '-', '-', '--', '--', '--', '--', '--', '--', '-']
linewidths = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
axisPR     = [[0.0, 1.0, 0.8, 1.0], [0.0, 1.0, 0.5, 0.95], [0.0, 1.0, 0.5, 1.0], [0.0, 1.0, 0.8, 1.0], [0.0, 1.0, 0.3, 0.9]]
axisFT     = [[0.0, 255.0, 0.75, 0.95], [0.0, 255.0, 0.70, 0.88], [0.0, 255.0, 0.6, 0.9], [0.0, 255.0, 0.7, 0.95], [0.0, 255.0, 0.60, 0.83]]

plt.subplots_adjust(top=0.95, left=0.04, bottom=0.06, right=0.995,  wspace =0.2, hspace =0.3)
flag = True
for i, data in enumerate(dataset):
    plt.subplot(2,5,1+i)
    for j, algo in enumerate(algorithm):
        recall    = sio.loadmat('../result/'+algo+'/'+data+'/rec.mat')['rec'][0]
        precision = sio.loadmat('../result/'+algo+'/'+data+'/prec.mat')['prec'][0]
        plt.plot(recall, precision, color=colors[j], linestyle=linestyles[j], linewidth=linewidths[j], label=algo)
        plt.axis(axisPR[i])
    plt.title(data, fontsize=12)
    plt.xlabel('Recall', fontsize=12)
    if flag:
        flag = False
        plt.ylabel('Precision', fontsize=12)
    plt.grid(ls='--')
    plt.legend(loc="lower left", fontsize=9)


flag = True
for i, data in enumerate(dataset):
    plt.subplot(2,5,6+i)
    for j, algo in enumerate(algorithm):
        precision = sio.loadmat('../result/'+algo+'/'+data+'/prec.mat')['prec'][0]
        recall    = sio.loadmat('../result/'+algo+'/'+data+'/rec.mat')['rec'][0]
        F_measure = 1.3*precision*recall/(0.3*precision+recall)
        plt.plot(np.linspace(0, 256, 256), F_measure, color=colors[j], linestyle=linestyles[j], linewidth=linewidths[j], label=algo)
        plt.axis(axisFT[i])

    plt.title(data, fontsize=12)
    plt.xlabel('Threshod', fontsize=12)
    if flag:
        flag = False
        plt.ylabel('F-measure', fontsize=12)
    plt.legend(loc="lower left", fontsize=9)
    plt.grid(ls='--')

plt.show()

**Comment by weijun-arc** [comment]
[curve.zip](https://github.com/weijun88/F3Net/files/5504847/curve.zip)
You may need to change some codes to adapt to your own project.

**Comment by ZhaiTianLin** [comment]
3Q
