### ISSUE TITLE
How to test code

### ISSUE THREAD

**Issue by ofirkris** [weijun88/F3Net#4]
Hi thanks for sharing your great work.

How do I run the code on my input images? where do I put my images for testing?

python3 test.py
returns the following error:
`TypeError: 'NoneType' object is not subscriptable`

**Comment by weijun-arc** [comment]
Sorry, this code doesn't support your own input images. If you want to test your own images, please format them according to the data folder(image folder + text.txt) and change the input path of src/test.py to your dataset.

**Comment by ofirkris** [comment]
Thanks, can you show an example of how to do this?
text.txt shows various numbers while data folder is empty.

**Comment by weijun-arc** [comment]
1. create a new folder named 'MY' in the ' data' folder
2. put your image in the data/MY/image folder
3. put your label in the data/MY/mask folder
4. write the image name without suffix into the data/MY/test.txt
5. change the input path of src/test.py

This code is built to show the results of datasets in the paper. If you have other needs, you may need to read the code and change it according to your requirements.
