### ISSUE TITLE
关于model-32是在那个数据集上训练得到的？

### ISSUE THREAD

**Issue by zhangbanxian123** [weijun88/F3Net#5]
我根据您提供的model-32预训练模型进行了测试，得到了非常满意的效果，非常感谢你提供的源码。
但是我想知道model-32是在哪个数据集上预训练得到的？我看到train.py文件中为DUTS数据集，不知道是不是呢？
期待回答。

**Comment by weijun-arc** [comment]
是的，我们在imagenet预训练的resnet50使用DUTS数据集训练得到了model-32



---原始邮件---
发件人: "BanXian Zhang"<notifications@github.com&gt;
发送时间: 2020年1月15日(周三) 上午9:47
收件人: "weijun88/F3Net"<F3Net@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [weijun88/F3Net] 关于model-32是在那个数据集上训练得到的？ (#5)



我根据您提供的model-32预训练模型进行了测试，得到了非常满意的效果，非常感谢你提供的源码。
 但是我像只到model-32是在哪个数据集上预训练得到的？我看到train.py文件中为DUTS数据集，不知道是不是呢？
 期待回答。

**Comment by zhangbanxian123** [comment]
我猜想将你提供的多个数据集一起训练，会不会对检测效果有更进一步的提升 ^0^

**Comment by weijun-arc** [comment]
为了实验的公平性，我们需要和其它论文一样使用同样的训练集和测试集，如果你只是想提升性能，增加数据不失为一种方式
