### ISSUE TITLE
How to get the Fig.3 in paper?

### ISSUE THREAD

**Issue by lartpang** [weijun88/F3Net#6]
![image](https://user-images.githubusercontent.com/26847524/73756314-51bf7f80-47a2-11ea-8225-9c0ddbd725b6.png)

How to get it? Can you give some code about it? Thanks. It's a great work...

**Comment by lartpang** [comment]
OK, I think, the alpha is the following item, it's right?

![image](https://user-images.githubusercontent.com/26847524/73757319-0908c600-47a4-11ea-94db-d4a477a68bc0.png)

**Comment by ghost** [comment]
I suppose it's a solution
`torch.abs(F.avg_pool2d(mask, kernel_size=31, stride=1, padding=15)-mask)`
mask is ground truth
